name: Lint

on:
  # push:
  #   branches:
  #     - main
  # pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tflint:
    name: TFLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: TFLint
        uses: docker://wata727/tflint

  fmt:
    name: Code Format
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:latest
    steps:
      - uses: actions/checkout@master
      - run: terraform fmt --recursive -check=true

  docs:
    name: Docs
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Deps
        run: brew update && brew install pre-commit terraform-docs terraform
      - name: Check Docs
        run: pre-commit run --show-diff-on-failure --all-files terraform_docs

  validate:
    name: Validate
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:{{ cookiecutter.tf_version }}
    steps:
      - uses: actions/checkout@master
      - name: Validate Code
        env:
          {%- if cookiecutter.use_aws_provider == "y" %}
          AWS_REGION: 'us-west-2'
          {%- endif %}
          TF_WARN_OUTPUT_ERRORS: 1
        run: |
          terraform init
          terraform validate
      - name: Validate Examples
        run: |
          for example in $(find examples -maxdepth 1 -mindepth 1 -type d); do
            cd $example
            terraform init
            terraform validate
            cd -
          done

  minimum:
    name: Minimum version check
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:{{ cookiecutter.tf_version }}
    steps:
      - uses: actions/checkout@master
      - name: Validate Code
        env:
          {%- if cookiecutter.use_aws_provider == "y" %}
          AWS_REGION: 'us-west-2'
          {%- endif %}
          TF_WARN_OUTPUT_ERRORS: 1
        run: |
          sed -i -e 's/>=/=/' -e 's/ \(\d\+\.\d\+\)"/ \1.0"/' versions.tf
          terraform init
          terraform validate
