repos:
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.43.0
  hooks:
    - id: terraform_fmt
      stages: [commit]
    - id: terraform_validate
      stages: [commit]
    - id: terraform_tflint
      stages: [commit]
    {%- if cookiecutter.use_aws_provider == "y" %}
    - id: terraform_tfsec
      stages: [commit]
    {%- endif %}
    - id: terraform_docs
      stages: [commit]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: end-of-file-fixer
      stages: [commit]
    - id: trailing-whitespace
      stages: [commit]
    - id: check-merge-conflict
      stages: [commit]
    {%- if cookiecutter.use_aws_provider == "y" %}
    - id: detect-aws-credentials
      stages: [commit]
    {%- endif %}
